### ISSUE TITLE
Windows: fatal error C1001: An internal error has occurred in the compiler.

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/node-mapnik#596] opened 2016-02-12 13:52 UTC
`mapnik@master` and `node-mapnik@master` as of now.

```
 c:\mb\windows-builds-64\packages\node-mapnik\mapnik-sdk\include\mapnik/symbolizer_base.hpp(104): note: see reference to function
   template instantiation 'mapnik::util::variant<mapnik::value_bool,mapnik::value_integer,mapnik::enumeration_wrapper,mapnik::valu
  e_double,std::string,mapnik::color,mapnik::expression_ptr,mapnik::path_expression_ptr,mapnik::transform_type,mapnik::text_placem
  ents_ptr,mapnik::dash_array,mapnik::raster_colorizer_ptr,mapnik::group_symbolizer_properties_ptr,mapnik::font_feature_settings>:
  :variant<const char*&,mapbox::util::detail::value_traits<T,mapnik::value_bool,mapnik::value_integer,mapnik::enumeration_wrapper,
  mapnik::value_double,std::string,mapnik::color,mapnik::expression_ptr,mapnik::path_expression_ptr,mapnik::transform_type,mapnik:
  :text_placements_ptr,mapnik::dash_array,mapnik::raster_colorizer_ptr,mapnik::group_symbolizer_properties_ptr,mapnik::font_featur
  e_settings>,void>(const char *&) noexcept' being compiled
          with
          [
              T=const char *&
          ] (compiling source file ..\src\mapnik_map.cpp)
..\src\mapnik_vector_tile.cpp(2706): warning C4101: 'ex': unreferenced local variable [c:\mb\windows-builds-64\packages\node-mapni k\build\mapnik.vcxproj]
..\src\mapnik_vector_tile.cpp(3650): fatal error C1001: An internal error has occurred in the compiler. [c:\mb\windows-builds-64\p ackages\node-mapnik\build\mapnik.vcxproj]
  (compiler file 'msc1.cpp', line 1421)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  Please choose the Technical Support command on the Visual C++
   Help menu, or open the Technical Support help file for more information
  ..\src\mapnik_vector_tile.cpp(3650): note: while compiling class template member function 'mapnik::util::variant<Image *,CairoSu
  rface *,Grid *>::variant<nullptr,mapbox::util::detail::value_traits<T,Image *,CairoSurface *,Grid *>,void>(nullptr &&) noexcept(
  <expr>)'
          with
          [
              T=nullptr
          ]
  Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe.  You will be prompted to sen
  d an error report to Microsoft later.
  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
cl : Command line error D8040: error creating or communicating with child process [c:\mb\windows-builds-64\packages\node-mapnik\bu ild\mapnik.vcxproj]
```

Possible hints:

* optimization settings with VS2015 Update 1:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/ea74ee2b-3c8b-4b55-ab0b-9ec5d6f9acef/compiler-bug-in-vs-2015-when-using-code-analyzer-on-kernel-driver-c-code-project?forum=vsdebug
https://msdn.microsoft.com/en-us/library/y19zxzb2.aspx?f=255&MSPPError=-2147217396
https://connect.microsoft.com/VisualStudio/feedback/details/813086/c1xx-fatal-error-c1001-an-internal-error-has-occurred-in-the-compiler

* compiler out of heap memory
https://support.microsoft.com/en-us/kb/195738

**Comment by BergWerkGIS** [comment] 2016-02-12 14:15
Doesn't seem to be the optimization. 

Currently we [don't have optimization specified explicitly](https://github.com/mapnik/node-mapnik/blob/5b2d6d50fa0f0c6e5f4423b02541ebe8bd128aee/common.gypi#L54), but tried with

* `0`: off
* `2`: speed
* `3`: full

same error.

**Comment by lightmare** [comment] 2016-02-12 21:35
Alas, more ICE! I'd try this to make it easier for the compiler:
 - change void to something else here: https://github.com/mapbox/variant/blob/5aab5df0dc899b484c04ce9c649645787ee0bc5c/variant.hpp#L127 -- maybe it doesn't like void in tuple, you can change it any other type, it's not used
 - if that doesn't help, remove noexcept here: https://github.com/mapbox/variant/blob/5aab5df0dc899b484c04ce9c649645787ee0bc5c/variant.hpp#L589 -- in case it has trouble with `is_nothrow_constructible`
 - I'd also check whether `is_same, is_convertible` work well with `nullptr_t`

**Comment by springmeyer** [comment] 2016-02-16 21:37
@BergWerkGIS - I just looked into this a bit. I'm feeling like the use of `mapbox::variant` here is not mandatory. If this is the only place this compiler problem is happening we could workaround but using raw pointers and dropping variant usage. Of course that would just dodge the problem and it is likely work fully fixing in variant - just really hard to do that given we'd need to reduce a testcase for what is happening and what is happening is a compiler crash not a clear code error.

So I think the best route here is to troubleshoot this in node-mapnik. Could you create a branch of node-mapnik that points at a Mapnik master SDK then ping me. I'll then poke by committing to that branch and letting appveyor tell me if we've dodged the issue.

**Comment by springmeyer** [comment] 2016-02-16 22:52
> Could you create a branch of node-mapnik that points at a Mapnik master SDK then ping me?

@BergWerkGIS - nevermind! I got this and bumped to start testing in 238035e

**Comment by springmeyer** [comment] 2016-02-17 01:11
That commit passed: https://github.com/mapnik/node-mapnik/commit/238035eae44f2d95c63efd05822a86edc8096ef8. I assumed it would fail and the original compiler error would be replicated. Not sure why not....

**Comment by springmeyer** [comment] 2016-02-18 23:30
@BergWerkGIS - let me know when you've had a chance to test to see if you can still replicate this.

**Comment by BergWerkGIS** [comment] 2016-02-19 13:26
@springmeyer sorry, forgot to report back yesterday.

Tried again today on *three* different machines.

Built `all deps`, `mapnik` and `node-mapnik` from scratch.

Interestingly `node-mapnik` _fails on all of them_ when using the locally created mapnik SDK.
Also tried `node@0.10.40/0.12.7/5.1.0` -> all fail.

However, if I use `mapnik-win-sdk-v3.0.9-246-gd751731-x64-14.0.7z` (created 3 days ago by the same scripts), which also gets pulled in by AppVeyor, _the build succeeds_.

-----------

My current hunch: `Visual Studio 2015 Update 1` which I have installed on all local machines but neither on our build server nor on AppVeyor.


Maybe `Update 1` creates a `mapnik SDK` that does work on its own but not in conjunction with `node-mapnik` (clash of some optimization or other settings???).

Also interesting that `Visual Studio 2015 Update 1` is able to build `node-mapnik` with a `mapnik SDK` created by stock `Visual Studio 2015`.

**Comment by BergWerkGIS** [comment] 2016-02-24 17:03
Could this be why `node-mapnik` is failing to build on Windows and that VS is unable to determine dependent names apart from non-dependent names?

[Partial Support for Expression SFINAE in VS 2015 Update 1](https://blogs.msdn.microsoft.com/vcblog/2015/12/02/partial-support-for-expression-sfinae-in-vs-2015-update-1/)

Especially the ["unsupported section"](https://blogs.msdn.microsoft.com/vcblog/2015/12/02/partial-support-for-expression-sfinae-in-vs-2015-update-1/#unsupported).

**Comment by lightmare** [comment] 2016-02-24 20:03
Can you confirm that the error is not caused by initializing the variant with `nullptr`?

Regardless of the above, I think this is where `no_init` might actually be useful. But for that to work, visitation of uninitialized variant would have to do something other than attempt (and fail) to visit the last alternative. I'll submit an issue at variant.

**Comment by springmeyer** [comment] 2016-02-24 20:21
@lightmare - good clues.

@BergWerkGIS - you were going to diff out the differences in the Mapnik SDK that crashes vs not - what was the outcome of that investigation?

Also @BergWerkGIS @artemp will ping you in the morning to try debugging interactively with a few ideas that might help.

**Comment by artemp** [comment] 2016-02-24 20:56
Here is my rough plan to try tomorrow with @BergWerkGIS : 

* First thing first - Lets get a _diff_ to see if code is different between local build and AppVeyor 
/cc @BergWerkGIS ^.  

* Second - lets try something like this to avoid initialising variant with `nullptr` 

```c++
struct dummy {};
using surface_type = mapnik::util::variant<
    dummy,
    Image *
  , CairoSurface *
#if defined(GRID_RENDERER)
  , Grid *
#endif
  >;
```

In `vector_tile_render_baton_t` constructor replace `surface(nullptr)` with `surface() ` + amend `struct deref_visitor` 
 
* Third - storing raw pointers in variant doesn't look like a good idea anyways

**Comment by BergWerkGIS** [comment] 2016-02-24 21:16
Diff: Not exactly sure how that happened, but old variant made it into the SDK that already should have contained a new one.

* SDK that worked: `variant@0.1.0`
* SDK that fails: `variant@1.1.0`

I updated the build chain with a new SDK.
Now AppVeyor fails with the same error: 

```
 ..\src\mapnik_vector_tile.cpp(3650): note: while compiling class template member function 'mapnik::util::variant<Image *,CairoSurface *,Grid *>::variant<nullptr,mapbox::util::detail::value_traits<T,Image *,CairoSurface *,Grid *>,void>(nullptr &&) noexcept(<expr>)'
          with
          [
              T=nullptr
          ]
  Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe.  You will be prompted to send an error report to Microsoft later.
cl : Command line error D8040: error creating or communicating with child process [C:\projects\node-mapnik\build\mapnik.vcxproj]
```

https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.1242/job/m3n76h4mg5oqinjp#L405

**Comment by BergWerkGIS** [comment] 2016-02-24 21:17
Forgot, all tests passed with https://github.com/mapbox/variant/compare/crazy_usage

**Comment by BergWerkGIS** [comment] 2016-02-24 21:29
> Can you confirm that the error is not caused by initializing the variant with `nullptr`?

y, also found a reference that VS compiler doesn't like that, but haven't checked yet.

**Comment by springmeyer** [comment] 2016-02-25 00:00
Okay, thanks @BergWerkGIS - so sounds like:

   - The reason it was tricky to replicate is different variant versions at play
   - It is the new (and latest) variant release that is problematic

Therefore despite this being a compiler crash (a compiler should never crash) I think variant is likely partly to blame. So the idea above with @artemp is a good next step. I also see that @lightmare created https://github.com/mapbox/variant/pull/93 which might be another thing to try. Both might workaround the problem.

I presume that you can easily test workarounds by:

   - Manually editing the `variant.hpp` inside the Mapnik SDK
   - Rebuilding node-mapnik

So: you should not need to recompile Mapnik core to iterate on testing tomorrow.

**Comment by lightmare** [comment] 2016-02-25 00:11
The MSVC compiler has a really hard time with some C++11 features, `noexcept` being one of them. Yesterday I tried inheriting variant's constructors in image_view_any and got another ICE https://github.com/lightmare/mapnik/commit/84f16bb9f19ca6b45f279623b31aa7861d2178fa -- might be completely unrelated, but the error mentioned a constructor template with noexcept...

**Comment by BergWerkGIS** [comment] 2016-02-25 08:26
All :white_check_mark: 

Only change needed was:

`surface(nullptr)` => `surface()`

https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.1243
https://travis-ci.org/mapnik/node-mapnik/builds/111685697

Maybe compiler was not able to infer the type of `Nan::ObjectWrap::CairoSurface(nullptr)` object?

----

Alsot tried https://github.com/mapbox/variant/pull/93 but that crashed the compiler like before (with un-modified `node-mapik`).

**Comment by artemp** [comment] 2016-02-25 08:36
@BergWerkGIS - sounds good ^ . Using an extra `Dummy` type would be a better solution to avoid default constructed `Image`.  I'll push a change in a few.

**Comment by lightmare** [comment] 2016-02-25 10:43
> Alsot tried mapbox/variant#93 but that crashed the compiler like before (with un-modified node-mapik).

That was not supposed to fix the issue by itself. It will only allow you to keep variant uninitialized and not blow up when visited, i.e.:
```c++
surface(mapbox::util::no_init) // instead of surface(nullptr)
```
```c++
struct deref_visitor
{
    void operator() (/* no arg*/) {} // no-op, this is called when uninitialized
    template <typename SurfaceType>
    void operator() (SurfaceType * surface)
    ...
};
```

**Comment by springmeyer** [comment] 2016-02-25 15:20
Thanks for everyones efforts here. So before closing this a few followup questions:

  - @artemp why was a dummy type needed like added in https://github.com/mapnik/node-mapnik/commit/bd158451c510b6ae3d0009a19e6302c0fdf5b5be when @BergWerkGIS said above that `Only change needed was: surface(nullptr) => surface()`
  - We need a test for this problem in variant. @BergWerkGIS / @artemp now that you understand the problem can you figure out how to get https://github.com/mapbox/variant/tree/crazy_usage to trigger the compiler crash?

**Comment by artemp** [comment] 2016-02-25 15:28
> `Only change needed was: surface(nullptr) => surface()` because relying on nullptr is a not a smart idea and it breaks strong typing and trips MSVC etc etc. So having a `dummy` struct is a totally sound approach in this case. It also easy to understand and follow in my opinion. As @lightmare suggested above `no_init` might be a better fit but I'd like to review changes to variant, also we'll need to do a formal release I guess aka 1.1.1 ? 

@springmeyer ^

**Comment by springmeyer** [comment] 2016-02-25 15:33
Thanks @artemp. Sounds like then:

  - variant `v1.1.0` is good enough for now
  - therefore lets move on https://github.com/mapnik/mapnik/issues/3297
  - node-mapnik is now unblocked based on your fix
  - variant v1.1.1 could include `no_init` but only if we have solid tests on windows - let's discuss at https://github.com/mapbox/variant/pull/93

**Closed by springmeyer** 2016-02-25 15:33 UTC
