### ISSUE TITLE
Database/Datasource caching?

### ISSUE THREAD

**Issue by Plasik** [mapnik/node-mapnik#449] opened 2015-05-22 03:18 UTC
Love the project. I am using this with a database as a source of points and got tiling working with some examples. Although I am confused as to why each tile requires a database call.

My map starts out zoomed out so every datapoint is needed (~200,000) this take about 10 seconds for my query to complete and mapnik does a good job. But when I zoom in just one level it loads (~100,000) points which takes 6-8 seconds for my database to complete. And so on and so forth. Mapnik already had every datapoint, why doesn't it just cache that and reuse it rather than relying on a new query for each tile? The bottleneck here is my database and the dataset, not mapnik.

Why does mapnik do this? Are there ways to solve this problem? I am open to other plugins/support or even suggestions of a cache service that will take my resultset and keep it in memory for mapnik to read,

**Comment by springmeyer** [comment] 2015-05-22 04:04
This is by design. A key aspect of Mapnik's performance is its ability to support multithreaded rendering and to not bloat memory usage. Caching data to try to predict user behavior for what zoom levels are needed would fight against the ability for low-memory parallel rendering.

So, as you guess the solution is not for Mapnik to cache but for you to cache. So, how to cache the results of database queries? Well there are many ways. What I recommend is vector tiles. Jumping ahead: the fastest rendering of millions of points can be done with `node-mapnik` + Mapnik's `dot` symbolizer + vector tiles created with https://github.com/mapbox/tippecanoe (which has sophisticated point filtering to throw on points that will not be seen). This is how the map at https://www.mapbox.com/blog/twitter-map-every-tweet/ is able to be rendered on the fly.

**Comment by Plasik** [comment] 2015-05-22 12:48
These are interesting things I didn't know existed.

I understand the design behind Mapnik, but at the same time I find the paradigm shift to be memory and storage is cheap and CPU and time to be expensive.

It seems a lot of hoops to jump through to take data from the database and convert it to GeoJSON so tippecanoe can parse it into a mbtiles format (which is just another database) and then feed that into Mapnik. Especially if I planning on having dynamic data at runtime for each map request, with no tile caching possible.

I have 32 GB memory at my disposal, and I was hoping there would be a flag or a setting I could adjust in Mapnik that would solve my problem internally (albeit I didnt expect it to be optimal as a third party caching schemes). The expense of developing a working and flawless solution that works nicely with 3-4 systems far outweighs the cost of just buying more RAM for a perhaps "dumb" but good enough solution.

Please consider it. Thanks!

**Comment by flippmoke** [comment] 2015-08-14 18:19
There is a lot of effort and design that is required in order to make a single datasource be access-able by different threads. I can promise you that we all have considered ways to make this possible, because every single person who uses this wants at times to make a large number of tiles. For several reasons, one of them development time, we have not been able to do anything like this. The biggest reason development time has not been put for this way is that vector tiles offer a more dynamic and better way for dealing with data, rather then having mapnik store a large dataset. 

You are much better off using vector tiles as described using tippecanoe (or making a tileset using mapnik) for performance reasons as well, this prevents the search + clipping time required for each dataset as it is already in a friendly format for rendering quickly.

**Comment by ddproxy** [comment] 2016-04-28 20:13
@flippmoke @Plasik I've successfully used pool2 to pool and cluster datasource connections based on variable parameters in the sql/table string for multi-threaded processes -> png/image generation. This can add vector (geojson/pbf) formats with the same workflow.

I can not attest to the overall performance yet since it's a POC and we've only hammered one node process with tile-requests.

I agree that vector tiles add more flexibility but the documentation for implementing them with and without datasource comparisons is quite sparse (in node). I had to review python and C documentation and source code to fully grok what was going on and even still I stumbled upon the datasource enabled vector tiles (solution) on my own. This is what precipitated the primary focus of PNG generation with optional pbf and geojson through the same workflow.

**Comment by springmeyer** [comment] 2017-09-09 22:59
Going to close this again. Don't see anything more to do here. Mapnik has a pluggable datasource system. Anyone wanting to cache data in memory should feel free to do that how they want, and then they can rig mapnik to read from that memory. At Mapbox we accomplish this in a highly parallelizable way over the network with vector tiles. Others that want to implement other solutions of feeding data into mapnik will likely need to use the Mapnik C++ API to accomplish this rather than node-mapnik.

@ddproxy would be great to have some links to what you accomplished as others may be very interesting. Can you post some?

**Closed by springmeyer** 2017-09-09 22:59 UTC
