### ISSUE TITLE
Build problem: 'is_valid' is not a member of 'mapnik'

### ISSUE THREAD

**Issue by knutole** [mapnik/node-mapnik#706] opened 2016-10-25 08:59 UTC
Running into this build error.

`package.json`: "mapnik": "^3.5.13"
`OS:` Ubuntu 14.04

`npm install --build-from-source mapnik`:

>   CXX(target) Release/obj.target/mapnik/src/mapnik_image_view.o
>   CXX(target) Release/obj.target/mapnik/src/mapnik_grid.o
> ../src/mapnik_grid.cpp: In constructor 'Grid::Grid(unsigned int, unsigned int, const string&)':
> ../src/mapnik_grid.cpp:57:75: warning: declaration of 'height' shadows a member of 'this' [-Wshadow]
>  Grid::Grid(unsigned int width, unsigned int height, std::string const& key) :
>                                                                            ^
> ../src/mapnik_grid.cpp:57:75: warning: declaration of 'width' shadows a member of 'this' [-Wshadow]
>   CXX(target) Release/obj.target/mapnik/src/mapnik_grid_view.o
>   CXX(target) Release/obj.target/mapnik/src/mapnik_memory_datasource.o
> ../src/mapnik_memory_datasource.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE MemoryDatasource::featureset(Nan::NAN_METHOD_ARGS_TYPE)':
> ../src/mapnik_memory_datasource.cpp:201:19: error: 'is_valid' is not a member of 'mapnik'
>          if (fs && mapnik::is_valid(fs))
>                    ^
> make: **\* [Release/obj.target/mapnik/src/mapnik_memory_datasource.o] Error 1
> make: Leaving directory `/mapic/modules/mile/node_modules/mapnik/build'
> gyp ERR! build error
> gyp ERR! stack Error:`make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
> gyp ERR! System Linux 4.4.20-moby
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/mapic/modules/mile/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik.node" "--module_name=mapnik" "--module_path=/mapic/modules/mile/node_modules/mapnik/lib/binding/node-v11-linux-x64"
> gyp ERR! cwd /mapic/modules/mile/node_modules/mapnik
> gyp ERR! node -v v0.10.40
> gyp ERR! node-gyp -v v2.0.1
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/mapic/modules/mile/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik.node --module_name=mapnik --module_path=/mapic/modules/mile/node_modules/mapnik/lib/binding/node-v11-linux-x64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mapic/modules/mile/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
> node-pre-gyp ERR! System Linux 4.4.20-moby
> node-pre-gyp ERR! command "node" "/mapic/modules/mile/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /mapic/modules/mile/node_modules/mapnik
> node-pre-gyp ERR! node -v v0.10.40
> node-pre-gyp ERR! node-pre-gyp -v v0.6.31
> node-pre-gyp ERR! not ok
> Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/mapic/modules/mile/node_modules/mapnik/lib/binding/node-v11-linux-x64/mapnik.node --module_name=mapnik --module_path=/mapic/modules/mile/node_modules/mapnik/lib/binding/node-v11-linux-x64' (1)

**Comment by tjwebb** [comment] 2017-01-19 06:01
same here.

**Comment by tjwebb** [comment] 2017-01-19 06:03
works for me with node 6.9

**Comment by lightmare** [comment] 2017-01-19 10:40
`is_valid` is only available with Boost >= 1.58. Ubuntu 14.04 comes with Boost 1.54 by default, upgradeable to 1.55 from default repositories, but any higher you'll need to build yourself.

**Comment by tjwebb** [comment] 2017-01-20 23:19
I'm seeing this same issue again, but I have boost 1.63 installed

**Comment by tjwebb** [comment] 2017-01-24 04:59
I think my problem was that I was using gcc compiler. I forced it to use clang 3.8 and it worked.

**Comment by flippmoke** [comment] 2017-01-24 16:54
Sometimes you might be finding the wrong version of the library due to some include path if you have more then one copy installed, which is always confusing. You can run with some minor edits exactly what the [travis script](https://github.com/mapnik/node-mapnik/blob/master/scripts/build_against_sdk.sh) for building which will pull in dependencies as well.

**Comment by YenTheFirst** [comment] 2017-02-02 19:27
I'm experiencing this same issue.

Reproducing the steps in `scripts/build_from_sdk.sh` results in a successful compile, but actually running anything fails with an undefined symbol error on `_ZN6mapnik3MapC1EiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE`

**Comment by springmeyer** [comment] 2017-02-02 19:54
@YenTheFirst that is a different issue. The problem is likely that you are on ubuntu trusty or xenial. So far the `buid_from_sdk.sh` has only been tested on ubuntu precise. To get it to work on trusty or xenial you'll likely need to add:

```
diff --git a/scripts/build_against_sdk.sh b/scripts/build_against_sdk.sh
index cc5c784..ff63734 100755
--- a/scripts/build_against_sdk.sh
+++ b/scripts/build_against_sdk.sh
@@ -63,7 +63,7 @@ if [[ ! `which node` ]]; then
 fi
 
 export LDFLAGS=${LDFLAGS:-""}
-export CXXFLAGS=${CXXFLAGS:-""}
+export CXXFLAGS="${CXXFLAGS:-""} -D_GLIBCXX_USE_CXX11_ABI=0"
 
 if [[ $UNAME == 'Linux' ]]; then
     export LDFLAGS='-Wl,-z,origin -Wl,-rpath=\$$ORIGIN '${LDFLAGS}
```

Can you test that and let me know if it resolved the problem? If so I'm happy to push that to master and can explain more about what is going on if you are interested.

**Comment by YenTheFirst** [comment] 2017-02-02 20:24
@springmeyer thanks. That flag, and using the downloaded SDK dependencies, seems to have resulted in a successful build.

Oddly enough, the system-installed libboost is version 1.58, so perhaps `is_valid` is newer, or there was some other compilation problem?

**Comment by flippmoke** [comment] 2017-02-21 16:42
I believe that `is_valid` came in boost 1.59 or later, in general it is best to update to the latest version of boost regularly due to bugs fixes that come with boost geometry. Closing ticket

**Closed by flippmoke** 2017-02-21 16:42 UTC
