### ISSUE TITLE
mapnik.blend throws errors when a callback is passed

### ISSUE THREAD

**Issue by rclark** [mapnik/node-mapnik#515] opened 2015-08-29 21:27 UTC
Generally the node.js expectation is that if a function takes a callback argument, then any errors will be passed to the callback function, instead of thrown. 

However there are [explicit tests in `blend.test.js`](https://github.com/mapnik/node-mapnik/blob/52c5f2a334719aef851401b6959d7942b3b05192/test/blend.test.js#L38-L54) that assert errors are thrown when the function is given a callback argument.

cc @flippmoke

**Comment by springmeyer** [comment] 2015-08-30 04:10
This is by design and I don't consider it a bug / worth changing.

> Generally the node.js expectation is that if a function takes a callback argument, then any errors will be passed to the callback function, instead of thrown.

This is not an assumption that node-mapnik holds to. And also not something other libraries hold to (take request for example). The convention in node-mapnik is that invalid arguments will throw a JS exception whereas if an error happens inside the thread pool then the callback will be passed an error.

**Comment by rclark** [comment] 2015-08-31 16:11
That's fine -- changing this behavior if it is the norm across node-mapnik is probably not a great idea. I do think its a difficult pattern for downstream libs to deal with. Consider this attempt to safely handle any errors coming from a call to `mapnik.blend`:

```js
function done(err, data) {
  if (err) return dealWithIt(err);
  else getOnWithIt(data);
}

try {
  mapnik.blend(input, done);
} catch (err) {
  return done(err);
}
```

vs. 

```js
mapnik.blend(input, function(err, data) {
  if (err) return dealWithIt(err);
  else getOnWithIt(data);
});
```

It **is** within the powers of the calling application to be aware of what valid inputs are and insure that it always sends valid inputs to node-mapnik functions. In that sense as long as the downstream lib doesn't make mistakes, then the `try` block isn't needed. But since when did downstream lib's never make mistakes? :wink:

**Comment by springmeyer** [comment] 2015-09-08 16:17
Closing this. I agree that error handling gets uglier when you both need a try/catch and to handle a callback, but thats a much larger issue than `mapnik.blend` and the case with all usage. If its worth change this overall we can revisit as a whole.

**Closed by springmeyer** 2015-09-08 16:17 UTC
