### ISSUE TITLE
Build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by BorisHollas** [mapnik/node-mapnik#662] opened 2016-06-26 20:47 UTC
With npm 3.5.2 and node.js 4.6.2, npm install mapnik@3.x fails.

[npm-debug.log.txt](https://github.com/mapnik/node-mapnik/files/333814/npm-debug.log.txt)

**Comment by BorisHollas** [comment] 2016-06-27 13:21
Likely related to #653

**Comment by springmeyer** [comment] 2016-09-03 17:17
That error is not descriptive enough to know what the problem is. All is see is `ENOENT` for spawn which means that a command which was shelled out to was not found. This was either node-pre-gyp (used for installing from binaries) or node-gyp (used for installing from source). It is not clear which was not found. Either way this seems like an npm bug to me and not anything specific to node-mapnik. I'm going to close this. Please upgrade to the latest node v4 version and see if it is fixed. If not please create a new issue with more details of how I can replicate.

**Closed by springmeyer** 2016-09-03 17:17 UTC

**Comment by math1985** [comment] 2016-09-18 19:55
I can replicate this issue. 

Replication:
* Install a fresh Ubuntu 16.04.
* sudo apt-get update
* sudo apt-get upgrade
* sudo apt-get install git nodejs npm
* git clone https://github.com/kosmtik/kosmtik.git
* cd kosmtik
*  npm install

Output:```

[...]
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mapnik@3.5.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mapnik@3.5.13 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mapnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matthijs/kosmtik/npm-debug.log

```

**Comment by math1985** [comment] 2016-09-18 19:56
Did anybody succeed in getting Mapnik/Kosmtik to run on 16.04?

**Comment by nebulon42** [comment] 2016-09-18 20:01
I did. But I have not tried with the bundled Node.js. I use the NodeSource repository: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by math1985** [comment] 2016-09-18 23:59
This problem can be solved with sudo apt-get install nodejs-legacy (perhaps in combination with uninstalling the regular nodejs).
