### ISSUE TITLE
Fail to install on FreeBSD

### ISSUE THREAD

**Issue by pnorman** [mapnik/node-mapnik#410] opened 2015-02-28 00:03 UTC
`npm install mapnik` fails with 

```
gmake: Entering directory '/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/build'
  ACTION binding_gyp_action_before_build_target_generate_protoc_files Release/obj/gen/vector_tile.pb.cc
  ACTION binding_gyp_action_before_build_target_generate_setting Release/obj/gen/mapnik_settings.js
  COPY /usr/home/pnorman/osm/kosmtik/node_modules/mapnik/lib/binding/node-v14-freebsd-x64/mapnik_settings.js
  TOUCH Release/obj.target/action_before_build.stamp
  CXX(target) Release/obj.target/mapnik/src/node_mapnik.o
gmake: g++: Command not found
mapnik.target.mk:188: recipe for target 'Release/obj.target/mapnik/src/node_mapnik.o' failed
gmake: *** [Release/obj.target/mapnik/src/node_mapnik.o] Error 127
gmake: Leaving directory '/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System FreeBSD 10.1-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=mapnik" "--configuration=Release" "--module_name=mapnik" "--version=1.4.17" "--major=1" "--minor=4" "--patch=17" "--runtime=node" "--node_abi=node-v14" "--platform=freebsd" "--target_platform=freebsd" "--arch=x64" "--target_arch=x64" "--module_main=./lib/mapnik.js" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/lib/binding/node-v14-freebsd-x64" "--module=/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/lib/binding/node-v14-freebsd-x64/mapnik.node" "--remote_path=./mapnik/v1.4.17/" "--package_name=node-v14-freebsd-x64.tar.gz" "--staged_tarball=build/stage/mapnik/v1.4.17/node-v14-freebsd-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/node-v14-freebsd-x64.tar.gz"
gyp ERR! cwd /usr/home/pnorman/osm/kosmtik/node_modules/mapnik
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=mapnik --configuration=Release --module_name=mapnik --version=1.4.17 --major=1 --minor=4 --patch=17 --runtime=node --node_abi=node-v14 --platform=freebsd --target_platform=freebsd --arch=x64 --target_arch=x64 --module_main=./lib/mapnik.js --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/lib/binding/node-v14-freebsd-x64 --module=/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/lib/binding/node-v14-freebsd-x64/mapnik.node --remote_path=./mapnik/v1.4.17/ --package_name=node-v14-freebsd-x64.tar.gz --staged_tarball=build/stage/mapnik/v1.4.17/node-v14-freebsd-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/node-v14-freebsd-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System FreeBSD 10.1-RELEASE
node-pre-gyp ERR! command "node" "/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/home/pnorman/osm/kosmtik/node_modules/mapnik
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.27
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=mapnik --configuration=Release --module_name=mapnik --version=1.4.17 --major=1 --minor=4 --patch=17 --runtime=node --node_abi=node-v14 --platform=freebsd --target_platform=freebsd --arch=x64 --target_arch=x64 --module_main=./lib/mapnik.js --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/lib/binding/node-v14-freebsd-x64 --module=/usr/home/pnorman/osm/kosmtik/node_modules/mapnik/lib/binding/node-v14-freebsd-x64/mapnik.node --remote_path=./mapnik/v1.4.17/ --package_name=node-v14-freebsd-x64.tar.gz --staged_tarball=build/stage/mapnik/v1.4.17/node-v14-freebsd-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/mapnik/v1.4.17/node-v14-freebsd-x64.tar.gz' (1)
npm ERR! FreeBSD 10.1-RELEASE
npm ERR! argv "node" "/usr/local/bin/npm" "install" "mapnik"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! mapnik@1.4.17 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@1.4.17 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the mapnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls mapnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/pnorman/osm/kosmtik/npm-debug.log
```

For reference, 
```
$ which clang++ # 3.3
/usr/bin/clang++
$ which clang++35
/usr/local/bin/clang++35
```

**Comment by springmeyer** [comment] 2015-03-02 02:28
The issue is:

> gmake: g++: Command not found

The workaround is to do:

```
export CXX=clang++
npm install mapnik --clang=1
```

More details at https://github.com/ncb000gt/node.bcrypt.js/issues/270#issuecomment-70419108.

I'll close this now since it has nothing specific to do with node-mapnik. You may hit other build issues related to freebsd (I only test on that platform very rarely, but certainly want to support it), so feel free to open up new issues with details.

**Closed by springmeyer** 2015-03-02 02:28 UTC
