### ISSUE TITLE
Cannot build if npm is too new?

### ISSUE THREAD

**Issue by BergWerkGIS** [mapnik/node-mapnik#487] opened 2015-07-29 13:47 UTC
Should probably posted to node/npm, but I start here, because this problem also appears on AppVeyor.

It seems that newer npm is not working with older node.exe.

Tried to build `node-mapnik` with `npm@v2.11.3` (comes with node@0.12.2) and node@
* 0.10.33 :x: 
* 0.10.36 :x: 
* 0.11.14 :x: 
* 0.12.0 :x: 
* 0.12.2 :white_check_mark: 

For node versions marked with :x: I get:

`no such file or directory 'c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib`

for almost every `npm` command, e.g.: `npm install -g node-gyp`
Directory does exist and current user has appropriate permissions.

### Full error

```
Error: ENOENT, no such file or directory 'c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib'

    at Error (native)
    at Object.fs.readdirSync (evalmachine.<anonymous>:691:18)
    at CachingRegistryClient.RegClient (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\index.js:50:6)
    at new CachingRegistryClient (C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache\caching-client.js:20:18)
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\npm.js:360:22
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:82:7
    at Array.forEach (native)
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:81:13
    at f (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
    at finalize (C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:200:5)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-gyp"
npm ERR! node v0.11.14
npm ERR! npm  v2.11.3
npm ERR! path c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall readdir

npm ERR! enoent ENOENT, no such file or directory 'c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
Error: ENOENT, no such file or directory 'c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib'

    at Error (native)
    at Object.fs.readdirSync (evalmachine.<anonymous>:691:18)
    at CachingRegistryClient.RegClient (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\index.js:50:6)
    at new CachingRegistryClient (C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache\caching-client.js:20:18)
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\npm.js:360:22
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:82:7
    at Array.forEach (native)
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:81:13
    at f (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
    at finalize (C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:200:5)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update" "-g" "node-gyp"
npm ERR! node v0.11.14
npm ERR! npm  v2.11.3
npm ERR! path c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall readdir

npm ERR! enoent ENOENT, no such file or directory 'c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
node_modules found
building node-mapnik
Error: ENOENT, no such file or directory 'c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib'

    at Error (native)
    at Object.fs.readdirSync (evalmachine.<anonymous>:691:18)
    at CachingRegistryClient.RegClient (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\index.js:50:6)
    at new CachingRegistryClient (C:\Program Files (x86)\nodejs\node_modules\npm\lib\cache\caching-client.js:20:18)
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\npm.js:360:22
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:82:7
    at Array.forEach (native)
    at C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:81:13
    at f (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\once\once.js:17:25)
    at finalize (C:\Program Files (x86)\nodejs\node_modules\npm\lib\config\core.js:200:5)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--build-from-source" "--msvs_version=2015" "--dist-url=https://s3.amazonaws.com/mapbox/node-cpp11" "--toolset=v140" "--loglevel=http"
npm ERR! node v0.11.14
npm ERR! npm  v2.11.3
npm ERR! path c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall readdir

npm ERR! enoent ENOENT, no such file or directory 'c:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-registry-client\lib'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by BergWerkGIS** [comment] 2015-07-29 14:36
Another AppVeyor problem:
[`node-gyp@2.0.2`](https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.625/job/06868ll9fxkk6598#L23) gets installed, but
[`node-gyp@1.0.3`](https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.625/job/06868ll9fxkk6598#L1167) is used, which doesn't know about `--msvs_version=2015` yet.

**Comment by springmeyer** [comment] 2015-07-29 19:26
Recapping my understanding:

 - node v0.12.2 works locally (and sounds like it does as well on appveyor)
 - other node versions are not viable to test yet until they are built with visual studio 2015. node v0.12.2 for node-cpp11 was manually published based on vs 2015 build by @BergWerkGIS. The rest need to be automated - waiting upstream on https://github.com/mapbox/node-cpp11/issues/23.
 - node-gyp version problems should be fixed by local install + https://github.com/mapnik/node-mapnik/commit/76c5ed6fadeb65deed5c763a1c1633f3be0f467c

**Comment by springmeyer** [comment] 2015-07-30 03:13
More updates:

> node v0.12.2 works locally (and sounds like it does as well on appveyor)

Also confirmed that node v0.12.7 built with vs 2015 and node-cpp11 also works and all tests pass.

> waiting upstream on mapbox/node-cpp11#23.

Now done.

After rebuilding node v0.10.40 with vs 2015 the npm errors described above went away. Or, maybe they are still there and I'm just not seeing them since I am hitting other errors sooner - described at https://github.com/mapnik/node-mapnik/issues/493.

**Comment by springmeyer** [comment] 2015-07-30 03:29
@BergWerkGIS - I don't know why node v0.10.x is not working on your frankfurt machine. I've run out of time and ideas tonight. One idea for you tomorrow to workaround: Install node v0.10.x globally and see if that fixes things? I think it might because the backtrace shows files in `C:\Program Files (x86)\nodejs` being broken - which is the global node v0.12.x install.

**Comment by BergWerkGIS** [comment] 2015-07-30 09:07
@springmeyer GOT IT!

Current error is: `Error: ENOENT, no such file or directory at Object.fs.readdirSync`

Remember the file and directory related patch, that was necessary for the CTPs?

With e.g. **0.10.40** we are patching `deps/uv/src/win/fs.c`: **`fmt = L"%ls*";` => `fmt = L"%S*";`** 
https://github.com/mapbox/node/compare/v0.10.40-release...mapbox:v0.10.40-nodecpp11#diff-4a14951fd12c46802543f3a8aa54a620L735

With 0.12.2 we didn't apply this patch this anymore, because the implementation of `fs.readDir` was completely changed.

I undid this `fs.c` patch locally and `npm install` is successful now (with "old" node and "new" npm).

More or less, as `*.cmd` of all modules get installed directly into the `node-mapnik` root directory.
But that's maybe due to my fiddeling with `%PATH%`.

**Comment by BergWerkGIS** [comment] 2015-07-30 15:19
@ 2nd mystery solved:

**older npm:**
it seems that `npm` didn't care where the executing `node.exe` was located. It installed all modules to the right place:
* just `npm install` => `./node_modules`
* `npm install -g` => either `ProgramFiles\nodejs` or `%APPDATA%`

So, our workaround of deleting ProgramFiles\nodejs\node.exe` and putting one into the local folder worked.

**newer npm:**
It looks like, that `npm` takes a hint, where the executing `node.exe` is located and uses that.

-----

### newer npm, with `node.exe` in `ProgramFiles`

<pre>
λ npm root
<b>C:\mb\node-mapnik\node_modules</b>
λ npm bin
<b>C:\mb\node-mapnik\node_modules\.bin</b>
λ npm root -g
<b>C:\Program Files (x86)\nodejs\node_modules</b>
λ npm bin -g
<b>C:\Program Files (x86)\nodejs</b>
</pre>

### now, *no* node.exe in ProgramFiles

<pre>
λ npm root
<b>C:\mb\node-mapnik\node_modules</b>
λ npm bin
<b>C:\mb\node-mapnik\node_modules\.bin</b>
λ npm root -g
<b>C:\mb\node-mapnik\node_modules <====!!!!</b>
λ npm bin -g
<b>C:\mb\node-mapnik <====!!!!</b>
</pre>

**Comment by springmeyer** [comment] 2015-07-30 15:27
perhaps we could start passing `--prefix` to get consistent/predicable behavior? https://docs.npmjs.com/files/folders#prefix-configuration and http://stackoverflow.com/a/14469516

**Comment by springmeyer** [comment] 2015-07-30 17:02
yay, fixed https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.649. Closing. I've just now added a lot of code comments (https://github.com/mapnik/node-mapnik/commit/2ac9c027999e37fadcc8c2b04b70aa19dc5fd512)  to capture how things are working now more clearly.

**Comment by springmeyer** [comment] 2015-07-30 17:03
Next action is merging https://github.com/mapnik/node-mapnik/pull/492

**Closed by springmeyer** 2015-07-30 17:02 UTC
