### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by iamvdo** [mapnik/node-mapnik#674] opened 2016-08-03 16:10 UTC
After installing the module (everything is good), when requiring from file:

```
require('mapnik')
```

I got this error:

```
module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: dlopen(/Users/iamvdo/Documents/Projets/MAPS/node_modules/mapnik/lib/binding/node-v48-darwin-x64/mapnik.node, 1): Library not loaded: /usr/local/lib/libmapnik.dylib
  Referenced from: /Users/iamvdo/Documents/Projets/MAPS/node_modules/mapnik/lib/binding/node-v48-darwin-x64/mapnik.node
  Reason: image not found
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/iamvdo/Documents/Projets/MAPS/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

OSX 10.11.5
Node 6.2.1
npm 3.9.3

Any clue? 
Thanks

**Comment by iamvdo** [comment] 2016-08-04 13:21
Updates after trying to install mapnik "by hand".

First using `brew install mapnik`, Everything's OK, but `require('mapnik')` fails with:

`Incompatible library version: mapnik.node requires version 3.0.11 or later [...]`

`mapnik-config -v` returns 3.0.9

Then, using `brew install mapnik --HEAD`, (`mapnik-config -v` now is 3.0.12) I get:

`Symbol not found: _WebPConfigInitInternal`

I also tried to build from source following [this tuto](http://mapnik.org/pages/downloads.html). Build fails with:

```
3 errors generated.
scons: *** [src/json/mapnik_json_geometry_grammar.o] Error 1
scons: building terminated because of errors.
make: *** [src/json/libmapnik-json.a] Error 2
```

I'm stuck. Any idea?

**Comment by andrelom** [comment] 2016-08-06 02:46
I get the same error, but the "Reason" error shows:
Reason: Incompatible library version: mapnik.node requires version 3.0.11 or later, but libmapnik.dylib provides version 3.0.9

**Comment by andrelom** [comment] 2016-08-06 03:23
I tried all the above steps, described by @iamvdo, and I have the same errors.

OSX 10.11.6
Node 6.3.1
npm 3.10.3

**Comment by lightmare** [comment] 2016-08-07 16:30
> 3 errors generated. scons: *** [src/json/mapnik_json_geometry_grammar.o] Error 1

What's the error message above this?

**Comment by iamvdo** [comment] 2016-08-07 17:36
The last block before error:
```
include/mapnik/json/geometry_grammar_impl.hpp:83:14: note: in instantiation of function template specialization 'boost::spirit::qi::rule<const char *, boost::spirit::locals<int,
      mapnik::util::variant<mapnik::json::empty, mapnik::geometry::point<double>, std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::vector<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::allocator<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > > > >, std::__1::vector<std::__1::vector<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::allocator<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > > > >, std::__1::allocator<std::__1::vector<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::allocator<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > > > > > > >, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>,
      mapnik::geometry::geometry<double> (), boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::tag::char_code<boost::spirit::tag::space, boost::spirit::char_encoding::standard> >, 0>,
      boost::spirit::unused_type>::operator=<boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater, boost::proto::argsns_::list2<const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater, boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::subscript,
      boost::proto::argsns_::list2<boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit, boost::fusion::vector<char> > >, 0> &, const
      boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::assign,
      boost::proto::argsns_::list2<boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::local_variable<0> >, 0>,
      boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<int>, 0> > >, 2> > &>, 2> &, const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::subscript, boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::modulus,
      boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::bitwise_or, boost::proto::argsns_::list2<const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::bitwise_or, boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::bitwise_or,
      boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater, boost::proto::argsns_::list2<const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater, boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit, boost::fusion::vector<char const (&)[7]> > >, 0> &, const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit, boost::fusion::vector<char>
      > >, 0> &>, 2> &, const boost::proto::exprns_::expr<boost::proto::tagns_::tag::subscript, boost::proto::argsns_::list2<boost::spirit::qi::symbols<char, int,
      boost::spirit::qi::tst<char, int>, boost::spirit::qi::tst_pass_through> &, const boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::assign,
      boost::proto::argsns_::list2<boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::local_variable<0> >, 0>,
      boost::phoenix::actor<boost::spirit::argument<0> > >, 2> > &>, 2> &>, 2> &, const boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater,
      boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater, boost::proto::argsns_::list2<const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit, boost::fusion::vector<char
      const (&)[14]> > >, 0> &, const boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit, boost::fusion::vector<char> > >, 0> &>, 2> &, const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::subscript, boost::proto::argsns_::list2<boost::spirit::qi::grammar<const char *,
      mapnik::util::variant<mapnik::json::empty, mapnik::geometry::point<double>, std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::vector<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::allocator<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > > > >, std::__1::vector<std::__1::vector<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::allocator<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > > > >, std::__1::allocator<std::__1::vector<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::allocator<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > > > > > > > (), boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::tag::char_code<boost::spirit::tag::space, boost::spirit::char_encoding::standard> >, 0>, boost::spirit::unused_type,
      boost::spirit::unused_type> &, const boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::assign,
      boost::proto::argsns_::list2<boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::local_variable<1> >, 0>,
      boost::phoenix::actor<boost::spirit::argument<0> > >, 2> > &>, 2> &>, 2> &>, 2> &, const boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater,
      boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater, boost::proto::argsns_::list2<const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater, boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::greater,
      boost::proto::argsns_::list2<const boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit, boost::fusion::vector<char const (&)[13]> > >, 0> &, const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit, boost::fusion::vector<char>
      > >, 0> &>, 2> &, const boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit,
      boost::fusion::vector<char> > >, 0> &>, 2> &, const boost::proto::exprns_::expr<boost::proto::tagns_::tag::subscript,
      boost::proto::argsns_::list2<boost::spirit::qi::rule<const char *, mapnik::geometry::geometry_collection<double> (),
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::tag::char_code<boost::spirit::tag::space,
      boost::spirit::char_encoding::standard> >, 0>, boost::spirit::unused_type, boost::spirit::unused_type> &, const
      boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::assign,
      boost::proto::argsns_::list2<boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::attribute<0> >, 0>,
      boost::phoenix::actor<boost::spirit::argument<0> > >, 2> > &>, 2> &>, 2> &, const boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit, boost::fusion::vector<char> > >, 0> &>, 2> &>, 2> &, const
      boost::proto::exprns_::expr<boost::proto::tagns_::tag::subscript, boost::proto::argsns_::list2<boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::tag::omit>, 0> &, boost::spirit::qi::rule<const char *, boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::tag::char_code<boost::spirit::tag::space, boost::spirit::char_encoding::standard> >, 0>, boost::spirit::unused_type,
      boost::spirit::unused_type, boost::spirit::unused_type> &>, 2> &>, 2> &, const boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal,
      boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit, boost::fusion::vector<char> > >, 0> &>, 2> &, const
      boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::phoenix::detail::tag::function_eval,
      boost::proto::argsns_::list4<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<mapnik::json::create_geometry_impl>, 0>,
      boost::phoenix::actor<boost::spirit::attribute<0> >, boost::phoenix::actor<boost::spirit::local_variable<0> >, boost::phoenix::actor<boost::spirit::local_variable<1> > >,
      4> > &>, 2> &>, 2> &, const boost::proto::exprns_::expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<boost::spirit::terminal_ex<boost::spirit::tag::lit,
      boost::fusion::vector<char> > >, 0> &>, 2> >' requested here
    geometry = lit('{')[_a = 0]
             ^
```

**Comment by lightmare** [comment] 2016-08-07 19:29
@iamvdo That points to where the error surfaced; perhaps related: https://github.com/mapnik/mapnik/commit/7b3f607a01f62ae8e173e778ac0d7267e7507a56
There should also be a line that says ` error: something useful` right after the filename.

**Comment by iamvdo** [comment] 2016-08-10 15:36
Oh yes, you're right. This is the error:
````
/usr/local/include/boost/spirit/home/qi/detail/alternative_function.hpp:30:40: error: no type named 'types' in 'boost::optional<boost::variant<int,
      mapnik::util::variant<mapnik::json::empty, mapnik::geometry::point<double>, std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::vector<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::allocator<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > > > >, std::__1::vector<std::__1::vector<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::allocator<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > > > >, std::__1::allocator<std::__1::vector<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > >, std::__1::allocator<std::__1::vector<mapnik::geometry::point<double>,
      std::__1::allocator<mapnik::geometry::point<double> > > > > > > >, mapnik::geometry::geometry_collection<double> > >'
        typedef typename variant_type::types types;
                ~~~~~~~~~~~~~~~~~~~~~~~^~~~~
```

**Comment by VVZen** [comment] 2016-08-16 09:52
MacOs 10.11.5, same errors as @iamvdo and @andrelom. Maybe it's an issue on the latest push?

**Comment by apaleja** [comment] 2016-08-17 17:29
facing same issue.

**Comment by tinayuangao** [comment] 2016-08-18 09:28
facing same issue.

**Comment by springmeyer** [comment] 2016-09-03 17:04
Sorry for the delay in replying here. The issue is that we don't provide node v6 binaries yet. So you can workaround this by sticking with node v4. For building from source you need the version of mapnik in the `package.json` for your given release.

Overall this will be solved by providing node v6 binaries, which will land once #634 is closed.

**Comment by springmeyer** [comment] 2016-09-09 21:11
Closing v3.5.14 will be tagged today once #634 is closed.

**Closed by springmeyer** 2016-09-09 21:11 UTC
