### ISSUE TITLE
Tiles in areas of "continuos" color are not rendered correctly 

### ISSUE THREAD

**Issue by averas** [mapnik/node-mapnik#433] opened 2015-04-13 19:52 UTC
I've created a mapnik configuration using Tilemill, and in Tilemill (latest version) everything looks great. When I use the same mapnik configuration with (latest) node-mapnik and (latest) tilelive something happens during rendering which causes homogeneously colored areas to generate miscolered tiles. I've fiddled with the meta tiles settings but that does not seem to affect the problem. This is what it looks like:

 
![screen shot 2015-04-13 at 21 39 58](https://cloud.githubusercontent.com/assets/1205805/7124146/25be266a-e227-11e4-814a-743b08d56a7a.png)
![screen shot 2015-04-13 at 21 39 42](https://cloud.githubusercontent.com/assets/1205805/7124147/25c233d6-e227-11e4-8bba-f34173a58b1e.png)

Any clues as to why this happens?

**Comment by springmeyer** [comment] 2015-04-13 23:06
What tilelive-backend are you usingand can you share your code? Are you using `tilelive-mapnik` for example? What is looks like is happening is that "solid color" tiles might be being cached, but returned from the cache incorrectly.

**Comment by averas** [comment] 2015-04-14 00:26
I've extracted the relevant parts and archived the whole thing (including the npm modules I use) here:
http://firefly.ibk.se/~racer/test_case.tgz
The file is pretty big because of the enclosed shapefile.

Perhaps looking at how I'm doing things is enough:

Server:
```javascript
var fs = require('fs');
var express = require('express');
var http = require('http');
var app = express(); 
var server = http.createServer(app);

var mapnik = require('mapnik');

if (mapnik.register_default_input_plugins) mapnik.register_default_input_plugins();
if (mapnik.register_default_fonts) mapnik.register_default_fonts();

var tilelive = require('tilelive');
require('tilelive-mapnik').registerProtocols(tilelive);

app.disable('etag');

fs.readFile('config.xml', function (err, xml) {
  tilelive.load({protocol: 'mapnik:', xml: xml.toString()}, function(err, source) {
    if (err) throw err;
    app.get('/:z/:x/:y.*', function(req, res) {
      source.getTile(req.param('z'), req.param('x'), req.param('y'), function(err, tile, headers) {
        if (!err) {
          res.set(headers)
          res.send(tile);
        } else {
          res.send('Tile rendering error: ' + err + '\n');
        }
      });
    });
  });
});

console.log('Listening on port: ' + 3001);
app.listen(3001);
```

config.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Map[]>
<Map srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over" background-color="#6b7e60" >

<Parameters>
  <Parameter name="format">png24</Parameter>
  <Parameter name="minzoom">1</Parameter>
  <Parameter name="maxzoom">19</Parameter>
  <Parameter name="scale">1</Parameter>
  <Parameter name="metatile">2</Parameter>
</Parameters>

<Style name="oceans" filter-mode="first">
  <Rule>
    <PolygonSymbolizer fill="#aaddff" />
  </Rule>
</Style>
<Layer name="oceans"
  srs="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over">
    <StyleName>oceans</StyleName>
    <Datasource>
       <Parameter name="file"><![CDATA[water_polygons.shp]]></Parameter>
       <Parameter name="type"><![CDATA[shape]]></Parameter>
    </Datasource>
  </Layer>

</Map>
```

**Comment by averas** [comment] 2015-04-15 08:45
My initial thought was that the shapefil was corrupt in some way, or that the mis-rendered tiles was due to the fact that there was no polygon edges in those tiles (so that there was no hit against the shapefile), but again, everything looks fine in tilemill...

**Comment by springmeyer** [comment] 2015-04-15 08:56
Can you try passing `internal_cache:false` to see if that fixes things? See this test for an example of how to do it: https://github.com/mapbox/tilelive-mapnik/commit/c1499105af5514f6255bdb479f8e6fa725e4a168#diff-4fa62c48cef2a5f2992ccabd6208a820R120

Also the `app.get` I think should be global. In other words you should ideally have the `fs.readFile` and `tilelive.load` calls happen synchronously when the script starts (using `queue(1)` via https://github.com/mbostock/queue would be an easy way to do this).

**Comment by averas** [comment] 2015-04-15 09:34
Thanks for the feedback - I'll look into the synchronous loading.

I tested with internal_cache:false which had no effect. Do you believe the asynchronous callbacks may be related to the issue?

**Comment by averas** [comment] 2015-04-20 07:33
Were you able to reproduce this issue?

**Comment by springmeyer** [comment] 2015-05-07 19:06
I've not tried to reproduce. My time is limited so to make it easy to reproduce I recommend you create a standalone test that includes a package.json and a sample HTML pages to test the server.

**Comment by mojodna** [comment] 2015-05-08 05:00
I may also be running into this with a raster layer in 3.2.0 (it goes away when zooming out 1):

![image](https://cloud.githubusercontent.com/assets/45/7530829/66b127e0-f504-11e4-99fb-b7547b7c177f.png)

I'll try to put together a standalone repro tomorrow.

**Comment by mojodna** [comment] 2015-05-08 05:33
This seems to have appeared between 3.1.6 and 3.2.0.

**Comment by springmeyer** [comment] 2015-05-08 05:40
@mojodna thanks for the details. does it go away if you change the type of png encoding. I wonder if https://github.com/mapnik/mapnik/pull/2671 could be related.

**Comment by mojodna** [comment] 2015-05-08 05:55
Having trouble overriding the PNG format.  `<Parameter name="format">png8;m=o</Parameter>` ??

However, it still shows up when outputting JPEGs:

![image](https://cloud.githubusercontent.com/assets/45/7531291/0417f61a-f50c-11e4-93f6-0fde09a3746e.png)

**Comment by mojodna** [comment] 2015-05-08 05:55
(In different places.)

**Comment by mojodna** [comment] 2015-05-08 06:03
Figured it out: `png8:m=o`, though both octree and hextree encoders are producing the same problems.

**Comment by mojodna** [comment] 2015-05-08 06:14
Using `png8:e=miniz` doesn't help either.

**Comment by springmeyer** [comment] 2015-05-08 06:19
okay. thanks for trying. would love a testcase if you can provide.

**Comment by mojodna** [comment] 2015-05-08 06:22
:+1: tomorrow :notes:

**Comment by springmeyer** [comment] 2015-05-08 19:32
@mojodna - are you also using tilelive-mapnik in this case?

If so can you try with https://github.com/mapbox/tilelive-mapnik/commit/37a96814534910b4b7df48ce2fad119edd7defe4 and see if you can still replicate? Before this change unless `autoLoadFonts` was explicitly set to false you'd get fonts being registered every time a source was created. In TileMill this is per tile so a lot of thread contention was happening.

If that does not fix - an you are using tilelive-mapnik - then it might be worth reverting https://github.com/mapbox/tilelive-mapnik/commit/1b2ae3883d9cd40efcaca1236cf0b60a967e0a5b#diff-92989f54c4804505d7ebdacce2a1a9b9 to see if that resolves.

Until there is an easy way for me to replicate I'm going to hold on debugging anymore.

**Comment by mojodna** [comment] 2015-05-08 19:34
Will do.

I got side-tracked on related pieces so I haven't been able to put a repro package together yet.  Soon.

**Comment by mojodna** [comment] 2015-05-08 22:31
Yes, tilelive-mapnik.  No more segfaults after https://github.com/mapbox/tilelive-mapnik/commit/37a96814534910b4b7df48ce2fad119edd7defe4 (w/ mapnik-3.3.0), at least on my Mac.

**Comment by mojodna** [comment] 2015-05-08 22:41
Forcibly disabling `tilelive-mapnik`'s solid cache resolves the issue.

**Comment by mojodna** [comment] 2015-05-08 22:42
...which points to `Image.view.isSolid` being the culprit.

**Comment by springmeyer** [comment] 2015-05-08 22:42
> Forcibly disabling tilelive-mapnik's solid cache resolves the issue.

Or maybe? https://github.com/mapbox/tilelive-mapnik/commit/a9cec13497f6ebdee96259c278765d6b742f351f#diff-92989f54c4804505d7ebdacce2a1a9b9

**Comment by mojodna** [comment] 2015-05-08 22:49
I don't think it's around module caching.  I was referring more to https://github.com/mapbox/tilelive-mapnik/blob/master/lib/render.js#L90

**Comment by springmeyer** [comment] 2015-05-08 22:54
@mojodna ah, right sorry. So, okay I think @flippmoke may have changed something around `isSolid`, but I can't tell right off from the changelog /cc @flippmoke. If I recall correctly the goal was to make consistent the interface between `image.isSolid` and `view.isSolid`.

**Comment by brianreavis** [comment] 2015-05-11 20:38
@springmeyer @mojodna We're also experiencing this on the latest version of node-mapnik. I'll try to do some digging too.

**Comment by brianreavis** [comment] 2015-05-11 21:22
This might be a different issue (if so please excuse), but it seems to be happening for Mapbox too:

![screenshot](https://cloud.githubusercontent.com/assets/118480/7575368/68284e7e-f7f1-11e4-8202-3cea2de3db6d.png)

**Comment by brianreavis** [comment] 2015-05-11 21:58
I think I managed to reproduce it with tests ([still waiting on travis atm](https://travis-ci.org/mapbox/tilelive-mapnik/builds/62149616)). Mapnik's `isSolid` seems to be returning the same "pixel" for tiles that should be different solid colors (e.g. land vs water). It took adjusting of the `metatile` setting to get it to happen consistently. In my case, the pixel it's returning for both land and water is `4293848814`.

**Comment by springmeyer** [comment] 2015-05-11 22:14
@brandonreavis - thanks for helping narrow this down. 

> This might be a different issue (if so please excuse)

Right, unrelated. The cause is a few vector tiles that incidentally contained geometry collections - we'll be fixing this week.

**Comment by flippmoke** [comment] 2015-05-11 23:23
I found out the problem for this, it has been corrected in core mapnik in:

https://github.com/mapnik/mapnik/commit/e44cdef805366be6c33c71ffd4ffe032f1b95ff4

A unit test for it was added in node-mapnik:

https://github.com/mapnik/node-mapnik/commit/8acecfde59081cf8b212c151b1fe704d988f8222

The problem revolved around image_views using `get_pixel` in mapnik core pulling from the x,y of the image, rather then with the offset x,y for the image view. This is now fixed.

**Closed by flippmoke** 2015-05-11 23:23 UTC

**Comment by springmeyer** [comment] 2015-05-11 23:37
Thanks @flippmoke for the fix, and for everyone's help uncovering this. Once travis recovers for the outage, I'll plan to publish binaries of the upcoming 3.3.1 release to ease testing.

**Comment by brianreavis** [comment] 2015-05-11 23:48
Excellent! Thanks @flippmoke @springmeyer

**Comment by mojodna** [comment] 2015-05-11 23:49
Hurrah!

**Comment by averas** [comment] 2015-05-12 08:13
Great work guys! Sorry I was unable to assist, I am on vacation along the Spanish coast...

**Comment by springmeyer** [comment] 2015-05-21 03:25
@averas if you want to test that this is fixed, you can try the upcoming release like:

```
"mapnik": "https://github.com/mapnik/node-mapnik/tarball/master"
```

That will pull in new binaries of v3.3.1-alpha that include @flippmoke's fix he mentions above.
