### ISSUE TITLE
Mapnik on AWS Lambda

### ISSUE THREAD

**Issue by adililhan** [mapnik/node-mapnik#849] opened 2018-02-12 13:11 UTC
Hi there,

I have an [issue](https://github.com/mapnik/mapnik/issues/3852) on `mapnik/mapnik` repository. I couldn't manage to deploy Mapnik to AWS Lambda.

@artemp suggests a solution for me. After that suggestion, the C++ version problem seems to be resolved. However, I got another error, which is related to node-mapnik.

```
START RequestId: e92829-0fcd-11e8-8c9f-d14a0e563b Version: $LATEST
2018-02-12T08:22:51.643Z	e92829-0fcd-11e8-8c9f-d14a0e563b	Error: Module version mismatch. Expected 48, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/node_modules/mapnik/lib/mapnik.js:31:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
END RequestId: e92829-0fcd-11e8-8c9f-d14a0e563b
REPORT RequestId: e92829-0fcd-11e8-8c9f-d14a0e563b	Duration: 1958.24 ms	Billed Duration: 2000 ms 	Memory Size: 128 MB	Max Memory Used: 32 MB	
RequestId: e92829-0fcd-11e8-8c9f-d14a0e563b Process exited before completing request
```

Would you please help me to resolve this issue?

**Comment by adililhan** [comment] 2018-02-13 14:02
@springmeyer do you have any idea about this issue? i have been trying to fix this issue for a while. i couldn't manage to compile node-mapnik appropriately.

**Comment by flippmoke** [comment] 2018-02-14 20:21
Closing as the issue is being addressed on the issue you linked above

**Closed by flippmoke** 2018-02-14 20:21 UTC

**Comment by springmeyer** [comment] 2018-02-28 19:35
starting docs at https://github.com/mapnik/node-mapnik/issues/863
